# Generated by Django 3.0.3 on 2020-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50)),
                ('donor_gender', models.CharField(max_length=10)),
                ('donors_blood_group', models.CharField(max_length=5)),
                ('donor_Volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('donor_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='receivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivers_name', models.CharField(max_length=50)),
                ('receivers_gender', models.CharField(max_length=10)),
                ('receivers_blood_group', models.CharField(max_length=5)),
                ('receivers_Volume', models.DecimalField(decimal_places=2, max_digits=5)),
                ('receivers_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_positive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('A_negative', models.DecimalField(decimal_places=2, max_digits=5)),
                ('B_positive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('B_negative', models.DecimalField(decimal_places=2, max_digits=5)),
                ('O_positive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('O_negative', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AB_positive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AB_negative', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
