# Generated by Django 3.0.3 on 2020-04-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blbd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='donor_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donors',
            name='donor_email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='receivers',
            name='receivers_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receivers',
            name='receivers_email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='AB_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='AB_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='A_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='A_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='B_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='B_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='O_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='O_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
