# Generated by Django 3.0.3 on 2020-04-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blbd', '0002_auto_20200423_0011'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donors',
            new_name='donor',
        ),
        migrations.RenameModel(
            old_name='receivers',
            new_name='receiver',
        ),
        migrations.RenameModel(
            old_name='stock',
            new_name='stocks',
        ),
    ]
