# Generated by Django 3.0.3 on 2020-04-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blbd', '0003_auto_20200423_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='AB_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='AB_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='A_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='A_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='B_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='B_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='O_negative',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='O_positive',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
